django_prometheus/exports.py
tests/test_exports.py

When attempting to use this with python 2, I ran in to a little snag. The following patch fixes the issue.

Fix endpoint on port range for python2

---

django_prometheus/utils.py

This uses `time.perf_counter` on Python 3.
On Python 2, it will use `time.clock` on Windows and `time.time` everywhere else.

Use timeit.default_timer as the timing function

---

django_prometheus/apps.py

The early database access (add application configuration time) in ExportMigrations() caused some trouble for us during testing (since the testing database won't have been started yet at this point), so here's a setting to disable it.

Add PROMETHEUS_EXPORT_MIGRATIONS (True) setting

---

django_prometheus/exports.py
requirements.txt

`gunicorn_config.py`
```
from prometheus_client import multiprocess
def child_exit(server, worker):
multiprocess.mark_process_dead(worker.pid)
workers = 5
```
Start command:
```
prometheus_multiproc_dir=metrics gunicorn -e 'prometheus_multiproc_dir=metrics' -c gunicorn_config.py example_project.wsgi
```
This makes the `/metrics` return an aggregate of the workers.

Support multiprocess collection

---

django_prometheus/middleware.py

Before this, in Django 1.7, if you submit a form with an `<input type="file" >`then reading `request.body` generates and error:
`RawPostDataException`
`You cannot access body after reading from request's data stream`
This uses `request.META['CONTENT_LENGTH']` instead of `request.body` to determine the request length in order to avoid this error.

Do not read request.body in middleware

---

django_prometheus/exports.py

Fixes https://github.com/korfuri/django-prometheus/issues/53
The change to support multiprocess broke the single process exposition as instead of using the default `core.REGISTRY` for `generate_latest()` registry argument, it was using a new blank `CollectorRegistry()`.

Use core.REGISTRY when in single process mode

---

.gitignore
.travis.yml
README.md
django_prometheus/cache/backends/django_memcached_consul.py
django_prometheus/cache/backends/filebased.py
django_prometheus/cache/backends/memcached.py
django_prometheus/cache/metrics.py
django_prometheus/tests/end2end/testapp/settings.py
django_prometheus/tests/end2end/testapp/test_caches.py
requirements.txt

Add a way to export metrics for get() for several caches backends. It's useful to keep track of the hit ratio.
Exemple output (everything):
```
django_cache_get_total{backend="filebased"} 26.0
django_cache_get_total{backend="django_memcached_consul"} 26.0
django_cache_get_hits_total{backend="django_memcached_consul"} 26.0
django_cache_get_hits_total{backend="filebased"} 25.0
django_cache_get_misses_total{backend="filebased"} 1.0
```

Added possibility to export metrics of several caches backends

---

django_prometheus/cache/backends/django_memcached_consul.py

Without this python tries to import itself (same file name as module name)

 Added compatibility with pypy

---

django_prometheus/cache/backends/django_memcached_consul.py
django_prometheus/cache/backends/filebased.py
django_prometheus/cache/backends/locmem.py
django_prometheus/cache/backends/memcached.py
django_prometheus/tests/end2end/testapp/test_caches.py

All cache wrapper ignore version param:
In [3]: cache.set('1', '1', version=1)
In [4]: cache.set('1', '2', version=2)
In [5]: cache.get('1', version=1)
Out[5]: '1'
In [6]: cache.get('1', version=2)
Out[6]: '1'

Fix cache version problem

---

requirements.txt
setup.py

Fixes https://github.com/korfuri/django-prometheus/issues/83
Simple dependency change that will fix tests and can be released as
a working package. Follow up can adapt to the interface and metric
name changes in 0.4.0 and depend on that version.

Pin prometheus-client to <0.4.0

---

django_prometheus/middleware.py
django_prometheus/testutils.py
requirements.txt

I've been way out of touch with this project, and I've seriously neglected its maintenance. I don't have a need for prometheus_client in my day job or elsewhere so it's hard for me to keep up with what the issues are. Still, there has been strong interest in keeping this working so I'd like to at least have passing tests and to be able to release the recent merges.
With the recently merged PRs (#103, #100) the tests still didn't pass. I've decided to just move forward with requiring a recent prometheus_client, because supporting super old APIs is a pain. Before I merge, I'd like to sollicit feedback from people who have been helping with the maintenance - @asherf @stealthybox @paweldudzinski @bz1 do you think it's acceptable to depend on the latest prometheus_client? Please object if not.

Upgrade to a recent prometheus client and fix tests

---

setup.py

Based on top of https://github.com/korfuri/django-prometheus/pull/105
fixes a mismatch in required Prometheus client version

match install_requires to requirements.txt

---

django_prometheus/tests/end2end/testapp/test_db.py

```
======================================================================
FAIL: testCounters (testapp.test_db.TestMysDbMetrics)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/travis/build/asherf/django-prometheus/django_prometheus/tests/end2end/testapp/test_db.py", line 104, in testCounters
cursor = connections['mysql'].cursor()
File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/django/test/testcases.py", line 144, in __call__
raise AssertionError(self.message)
AssertionError: Database queries to 'mysql' are not allowed in this test. Add 'mysql' to testapp.test_db.TestMysDbMetrics.databases to ensure proper test isolation and silence this failure. …
```

Fix issues with tests failing under Django 2.2

---

examples/prometheus/README.md

In the example the command given asks you to use prometheus.conf for your config.file, however, this file doesn't exist in the example. To keep consistent I've changed this.

Change config.file declaration from .conf to .yml

---

django_prometheus/exports.py
documentation/exports.md

`xrange` does not exist in Python 3 and Python 2 EOL is near

Use range instead of xrange for Python 3 compatibility

---

django_prometheus/exports.py
django_prometheus/tests/test_exports.py

I currently use a copypasta version of `SetupPrometheusEndpointOnPortRange()` that returns the port that was actually chosen from the range when starting the thread-based exporter. This is necessary because I need to dynamically register the exporter with a Consul agent for discovery of the Prometheus metrics endpoint for scraping. I figure there are probably other folks in similar situations.
This PR just returns the chosen port (an `int`), or if no ports are available, explicitly returns `None`.
Added a test for the case where no ports are available, modified the existing test for the case where a port is available.

Return the port chosen from port range in export setup

---

django_prometheus/middleware.py

The other side effect of this chance is that we delay the initialization and registration of the metrics object to the point in which Django creates the middleware instances.
This will allow for customization of the metrics, for example custom latency buckets.
See https://github.com/korfuri/django-prometheus/pull/75

Link metrics to middleware isntances.

---

README.md
django_prometheus/middleware.py
django_prometheus/tests/end2end/testapp/test_middleware_custom_labels.py

This allows applications to add labels to the metrics reported by middlewares.
this is done in a few steps.
1. Create an application class that inherits from the Metric class and overrides the register_metric mehtod to register metrics with the application sepcific labels.
2. Create an application class that inherits from the middleware class and overrides the label_metric method and attach the application specific labels to the relevant metrics.

Extensibility model for requests/response metrics.

---

README.md

Since Django<1.11 lists are used for `INSTALLED_APPS` and `MIDDLEWARE`.
Urls now also use a simplified path pattern, and [django.urls.re_path](https://docs.djangoproject.com/en/3.0/topics/http/urls/#using-regular-expressions) shall be used for regex matches.

Use lists in Django settings, use new url pattern

---

django_prometheus/cache/metrics.py
django_prometheus/conf/__init__.py
django_prometheus/db/metrics.py
django_prometheus/middleware.py
django_prometheus/migrations.py
django_prometheus/models.py

Availability add namespaces to metrics by adding PROMETHEUS_METRIC_NAMESPACE variable to django settings

configurable metric namespace

---

.travis.yml
django_prometheus/db/backends/postgis/base.py
django_prometheus/tests/end2end/testapp/settings.py
django_prometheus/tests/end2end/testapp/test_db.py

This adds support for PostGis database which is
also supported officially by django-- geodjango.
Refrences: https://github.com/korfuri/django-prometheus/pull/41 https://github.com/korfuri/django-prometheus/pull/90 https://github.com/korfuri/django-prometheus/pull/140

feat: Support for postgis database

---

django_prometheus/db/common.py

This bug causes the "type" label to be added to the ExportingCursorWrapper.labels dict, which is bad since the query_duration_seconds (for example) don't support the type label.

Fix issue w/ modifying passed labels dict.

---

django_prometheus/middleware.py

See the Django 3.1 release notes for information about deprecating the `Requests.is_ajax()` method.
```
django_prometheus/middleware.py:229: RemovedInDjango40Warning: request.is_ajax() is
deprecated. See Django 3.1 release notes for more details about this deprecation.
```
> The `HttpRequest.is_ajax()` method is deprecated as it relied on a jQuery-specific way of signifying AJAX calls, while current usage tends to use the JavaScript [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). Depending on your use case, you can either write your own AJAX detection method, or use the new [`HttpRequest.accepts()`](https://docs.djangoproject.com/en/3.1/ref/request-response/#django.http.HttpRequest.accepts) method if your code depends on the client `Accept` HTTP header.
>
> If you …

Fix Requests.is_ajax() deprecation warning in Django 3.1

---

django_prometheus/urls.py

Fix RemovedInDjango40Warning deprecation warning
https://code.djangoproject.com/ticket/31534

Replace deprecated django.conf.urls.url()

---

documentation/exports.md

Add a note to the exports documentation that one has to set `lazy-apps = true` (uWSGI) or `preload-app = false` (Gunicorn) in order to actually expose one metrics endpoint per process using the `PROMETHEUS_METRICS_EXPORT_PORT_RANGE` option.
See upstream issue https://github.com/korfuri/django-prometheus/issues/215

Add a note about required uWSGI/Gunicorn settings

---

django_prometheus/__init__.py

The old way of specifying the pre-release version results in a deprecation warning hence this change

fix dev/pre-release version

---

README.md
django_prometheus/tests/end2end/testapp/urls.py
documentation/exports.md

```  django_prometheus/tests/end2end/testapp/test_middleware.py::TestMiddlewareMetrics::test_exception_latency_histograms
/home/runner/work/django-prometheus/django-prometheus/django_prometheus/tests/end2end/testapp/urls.py:14: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
url(r"^admin/", admin.site.urls),
```
https://github.com/asherf/django-prometheus/runs/4127895607?check_suite_focus=true#step:8:857

Fix django deprecations

---

.github/workflows/ci.yml
django_prometheus/cache/backends/memcached.py
requirements.txt

MemcachedCache is being deprecated since `python-memcached` is not maintained (no release since 2017)
https://pypi.org/project/python-memcached/#history

Replace python-memcached with pylibmc

---

tox.ini

https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html#migrating-cli-options

remove deprecated isort option

---

django_prometheus/exports.py
documentation/exports.md

The variable name `prometheus_multiproc_dir` was deprecated in django-prometheus 0.10.0 in favor of `PROMETHEUS_MULTIPROC_DIR`.
fixes #275

Add support for uppercase PROMETHEUS_MULTIPROC_DIR

---

django_prometheus/cache/backends/memcached.py
django_prometheus/tests/end2end/testapp/settings.py
django_prometheus/tests/end2end/testapp/test_caches.py
django_prometheus/tests/test_testutils.py
django_prometheus/utils.py
requirements.txt
setup.py
update_version_from_git.py

When upgrading to Django 3.2, the django-prometheus package caused some issues because it forces the user to use the PyLibMCCache without making the implicit requirement of pylibmc transparent to the user or directly requiring the package (introduced by #296). Additionally, the deprecation warning is hidden from the user.
Django 3.2 gives the user the option to keep on using the deprecated backend, and also adds another cache backend than the pylibmc-based one.
This merge request adds support for all cache backends of Django 3.2 and lets the user choose between them according to the official Django documentation.
This closes issue #328

Support all cache backends of Django >=3.2

---

documentation/exports.md

A previous commit has allowed the PROMETHEUS_MULTIPROC_DIR env variable to be lower- and uppercase, however didn't reflect it in the documentation.

Updated outdated documentation

---

README.md
django_prometheus/conf/__init__.py
django_prometheus/db/metrics.py
django_prometheus/middleware.py

`django_http_requests_latency_including_middlewares_seconds` and `django_db_query_duration_seconds` don't use the `PROMETHEUS_LATENCY_BUCKETS` setting  and also the default for `django_http_requests_latency_seconds_by_view_method` is not the default that python prometheus client uses. 
I used the default that was used for `django_http_requests_latency_seconds_by_view_method` and moved it to conf module and then used that config in histograms mentioned above.

Fix two latency metrics not using PROMETHEUS_LATENCY_BUCKETS setting

---

django_prometheus/db/backends/common.py
django_prometheus/db/backends/postgis/base.py
django_prometheus/db/backends/postgresql/base.py

New version of django, ignore the `cursor_factory` connection param and override it after the connection is created:
see fix here: https://github.com/django/django/commit/0bc2bbf041df40a6ecb6262b2e5f3bb659dd8da8
the fix will be in 4.2.1 (unrelease) https://github.com/django/django/commit/0bc2bbf041df40a6ecb6262b2e5f3bb659dd8da8#diff-016044d83a0d01da55207c3122eb813b92093295894595570a7fb563546f2a32R22
at which point, this PR can be reverted.
follow up for https://github.com/korfuri/django-prometheus/pull/351

Refactor how we provide cursor factory

---

django_prometheus/db/backends/postgresql/base.py

PostgreSQL backend was somehow importing PostGIS, which caused unexpected import errors in Django users.

Fix postgres import

---

README.md

Add information about changing the namespace.

Update README.md for custom namespace

---

django_prometheus/cache/backends/redis.py
django_prometheus/tests/end2end/testapp/settings.py
django_prometheus/tests/end2end/testapp/test_caches.py

Django added Redis cache backend since 4.0.
I added the backend but I thinks maybe there is better way for naming! Now the old `django_redis` backend is called `RedisCache` (I left it intact for backward compatibility) and I named the new one `NativeRedisCache`.
If you thinks there is better option for naming or anything else, just let me know.
Thanks

Support Django's official Redis cache backend.

---

django_prometheus/cache/backends/memcached.py

When a falsy value is returned from cache via memcached backend, it returns None (the default) instead, of the cached value.
This is the same issue as with the Redis backend, which was fixed here: https://github.com/korfuri/django-prometheus/commit/1860549c3f8db1a0175995826404561f760369e2

Fix memcached return default on falsy values

---

CHANGELOG.md
README.md
django_prometheus/tests/end2end/testapp/settings.py
django_prometheus/tests/end2end/testapp/test_middleware.py
django_prometheus/tests/end2end/testapp/test_middleware_custom_labels.py
django_prometheus/tests/end2end/testapp/test_models.py
django_prometheus/tests/end2end/testapp/urls.py
django_prometheus/tests/end2end/testapp/views.py
pyproject.toml
requirements.txt
setup.cfg

This PR replaces Black, flak8 and isort with Ruff for format checking, reduces tooling.

replace black, flake8 and isort with ruff

---

.github/workflows/ci.yml
setup.py
tox.ini

Its EOL was Oct 2024: https://discuss.python.org/t/python-3-8-is-now-officially-eol/66983

Drop Python 3.8 Support

---

django_prometheus/cache/backends/redis.py
django_prometheus/db/backends/common.py
django_prometheus/db/backends/postgis/base.py
django_prometheus/db/backends/postgresql/base.py
django_prometheus/middleware.py
django_prometheus/tests/end2end/testapp/settings.py
django_prometheus/tests/end2end/testapp/test_caches.py
django_prometheus/tests/end2end/testapp/urls.py

Removes conditional blocks for unsupported Django versions and modernizes the code for Django 4.2 via django-upgrade.

EOL Django Cleaning

---

django_prometheus/cache/backends/redis.py

Fixed bug caused by trying to use global level logger variable from django_redis.cache that has been moved to django_redis.cache.RedisCache instance attribute since django-redis 4.12.0 release.
django-redis package allows to ignore cache exceptions by setting the `"IGNORE_EXCEPTIONS": True` key in the cache options in settings.py:
```
CACHES = {
"default": {
"OPTIONS": {
"IGNORE_EXCEPTIONS": True,
}
}
}
```
or by defining the following global variable in settings.py:
```
DJANGO_REDIS_IGNORE_EXCEPTIONS = True
```
When ignoring exceptions with `IGNORE_EXCEPTIONS` or `DJANGO_REDIS_IGNORE_EXCEPTIONS`, you may optionally log exceptions using the global variable `DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS` in your settings file:
```
DJANGO_REDIS_LOG_IGNORED_EXCEPTIONS = True
```
django_prometheus …

Fixed incompatibility with django-redis >= 4.12.0

---

requirements.txt

Django is supporting psycopg>3 since Django 4.2
> Django supports PostgreSQL 12 and higher. psycopg 3.1.8+ or psycopg2 2.8.4+ is required, though the latest psycopg 3.1.8+ is recommended.
https://docs.djangoproject.com/en/4.2/ref/databases/#postgresql-notes
Resolves:
- https://github.com/korfuri/django-prometheus/issues/410
Supersedes 
- https://github.com/korfuri/django-prometheus/pull/377/

Update psycopg version

---

.github/workflows/release.yml
.pre-commit-config.yaml
LICENSE
setup.py
tox.ini
update_version_from_git.py

Wraps `ruff` with pre-commit, adds basic pre-commit hooks and `django-upgrade`.

Use pre-commit framework for linters & formatters

---

CODE_OF_CONDUCT.md

This is a prerequisite for transferring this project into Django Commons. See #434 for previous discussions of the move to Django Commons.
https://github.com/django-commons/membership/issues/210 is the tracking issue for adoption.

Add the Django Commons code of conduct.

---

CHANGELOG.md
setup.py
tox.ini

Support for Django 5.0 ended by April 2025
https://upgradedjango.com/5.0/
Depends on:
- https://github.com/django-commons/django-prometheus/pull/476

Drop support for Django 5.0 (EOL)
