django_prometheus/urls.py
=> Fix Django 1.10 compatibility

.travis.yml, django_prometheus/db/common.py, django_prometheus/middleware.py, requirements.txt
This is the same as 
https://github.com/korfuri/django-prometheus/pull/30
To fix the 1.10 issue in https://github.com/korfuri/django-prometheus/issues/29
together with fixes to work with older versions.
=> Add MiddlewareMixin to both middlewares to fix django 1.10 2

.travis.yml, django_prometheus/middleware.py
Just convert the middlewares to PrometheusBeforeMiddleware(MiddlewareMixin) and PrometheusAfterMiddleware(MiddlewareMixin).
Related to issue #29
=> Add MiddlewareMixin to both middlewares to fix django 1.10

django_prometheus/db/backends/mysql/base.py, django_prometheus/db/backends/postgresql/base.py, django_prometheus/db/common.py
=> Fix cursor compatibility with Django 1.11

examples/prometheus/README.md
Update example README.md to use the correct markdown syntax for links.
=> Update example README.md

requirements.txt
It was preventing from testing
=> Bump version of pip-prometheus

django_prometheus/cache/backends/locmem.py, django_prometheus/tests/end2end/testapp/settings.py, django_prometheus/tests/end2end/testapp/test_caches.py
Implement a new backend as requested in #70 
cc: @korfuri
=> Implement metrics on locmem cache

README.md
see: https://github.com/asherf/django-prometheus/tree/badges#django-prometheus
=> Badge for supported python versions

documentation/exports.md
- Update uwsgi `_pidFunc` implementation to match new code structure from `promtheus_client`.
- Improve Grammar
- Add note about mounting configured dir as tmpfs
=> Update docs for prometheus_multiproc_dir

examples/prometheus/prometheus.yml
`labels` -> `external_labels`
`target_groups` -> `static_configs`
=> Update the example config so that it works

.travis.yml, requirements.txt, setup.cfg
https://pep8.readthedocs.io/en/release-1.7.x/#pep8-s-documentation
=> pep8 is deprecated, use pycodestyle

.travis.yml
Reverts korfuri/django-prometheus#154
=> Revert "Try deploy to test pypi."

.travis.yml, requirements.txt, tox.ini
closes https://github.com/korfuri/django-prometheus/issues/56
=> Switch to tox

README.md, django_prometheus/middleware.py
Based on https://github.com/korfuri/django-prometheus/pull/75 
closes https://github.com/korfuri/django-prometheus/issues/74
@kunalgrover05 FYI
=> Add custom latency buckets from Settings variable

django_prometheus/__init__.py, django_prometheus/middleware.py
closes https://github.com/korfuri/django-prometheus/issues/109
@travisgroth FYI
=> Use view as a label to be consistent with other labels

django_prometheus/middleware.py
I am working on the ability to extend the metrics reported by the middleware (by adding application specific labels) this is part of this work.
See https://github.com/korfuri/django-prometheus/pull/193 for full context
=> set metrics class as a class method so application can modify it.

django_prometheus/tests/end2end/testapp/helpers.py, django_prometheus/tests/end2end/testapp/settings.py
This is part of the extensibility work I am doing
see https://github.com/korfuri/django-prometheus/pull/193
=> Extract the logic to create middleware list for test app

README.md
Fixes: https://github.com/korfuri/django-prometheus/issues/207
=> Use MIDDLEWARE instead of MIDDLEWARE_CLASSES

django_prometheus/db/__init__.py, django_prometheus/db/common.py, django_prometheus/db/metrics.py, django_prometheus/tests/end2end/testapp/test_db.py
Hi,
I have added the DB query duration metric. I'm not sure it's a good idea and I have done it correctly.
Thanks
=> Add db query duration metric

django_prometheus/cache/backends/redis.py, requirements.txt
https://github.com/jazzband/django-redis/commit/b7d64f0a80180ecfe8900407fbdf5e4196fa7a2a
=> Upgrade django-redis

CHANGELOG.md, django_prometheus/__init__.py
Reverts korfuri/django-prometheus#234
=> Revert "Release 2.1.0"

documentation/exports.md
- Change `_pidFunc` argument to `process_identifier`
See issue #257
=> Update Exports documentation

django_prometheus/__init__.py
https://docs.djangoproject.com/en/3.2/releases/3.2/#what-s-new-in-django-3-2
=> Remove deprecation warning

django_prometheus/__init__.py, django_prometheus/apps.py, django_prometheus/cache/backends/django_memcached_consul.py, django_prometheus/cache/backends/filebased.py, django_prometheus/cache/backends/locmem.py, django_prometheus/cache/backends/memcached.py, django_prometheus/cache/backends/redis.py, django_prometheus/db/backends/mysql/base.py, django_prometheus/db/backends/postgis/base.py, django_prometheus/db/backends/postgresql/base.py, django_prometheus/db/backends/sqlite3/base.py, django_prometheus/exports.py, django_prometheus/middleware.py, django_prometheus/migrations.py, django_prometheus/tests/end2end/testapp/models.py, django_prometheus/tests/end2end/testapp/test_caches.py, django_prometheus/tests/end2end/testapp/test_db.py, django_prometheus/tests/end2end/testapp/test_middleware.py, django_prometheus/tests/end2end/testapp/test_middleware_custom_labels.py, django_prometheus/tests/end2end/testapp/test_migrations.py, django_prometheus/tests/end2end/testapp/test_models.py, django_prometheus/urls.py, setup.py, tox.ini
use the same version of isort in both places.
https://github.com/korfuri/django-prometheus/blob/fc11213516c6df63e6d92bf449080dbe7920755f/requirements.txt#L4
=> align isort reqs

CHANGELOG.md, django_prometheus/__init__.py
fixes: https://github.com/korfuri/django-prometheus/issues/306
=> Release v2.2.0

django_prometheus/apps.py
=> Make export of migrations False by default

CHANGELOG.md, django_prometheus/db/backends/postgis/base.py, django_prometheus/db/backends/postgresql/base.py, setup.py
See https://github.com/korfuri/django-prometheus/issues/350
=> add django 4.2 support

.github/workflows/ci.yml, CHANGELOG.md, pyproject.toml, requirements.txt, setup.py
Includes a cherry-pick of #362 and some fixes to get the tests to run.
=> Test on Django 5.0

django_prometheus/cache/backends/redis.py
Reverts korfuri/django-prometheus#416
=> Revert "Fixed incompatibility with django-redis >= 4.12.0"
